#!/bin/bash

startBuild()
{
ECR_REPO=891377352857.dkr.ecr.us-east-1.amazonaws.com/savior-tech
DOCKER_BUILD_TAG=$GIT_BRANCH-${BUILD_NUMBER}
docker build -t $ECR_REPO:$DOCKER_BUILD_TAG --pull=true .
if [ $? -eq 0 ]; then
echo "Docker build got success"
else
echo "Docker build was failed"
exit 1
fi
docker images -q $ECR_REPO
aws ecr get-login-password --region us-east-1 --profile new-kaaylabs | docker login --username AWS --password-stdin $ECR_REPO
IMAGE_ID=$(docker images -q $ECR_REPO | awk "NR==1{print $1}")
echo $IMAGE_ID
docker tag $IMAGE_ID $ECR_REPO:latest
docker inspect $IMAGE_ID
docker push $ECR_REPO:$DOCKER_BUILD_TAG && docker push $ECR_REPO:latest
if [ $? -eq 0 ]; then
echo "Docker Push got success"
docker logout
else
echo "Docker Push was failed"
docker logout
exit 1
fi
}

if [[ "$GIT_BRANCH" == "development" || "$GIT_BRANCH" == "uat" || "$GIT_BRANCH" == "preprod" ]];
then
DevBuild
elif [[ "$GIT_BRANCH" == "master" ]];
then
startBuild
else
echo "Skipping a build process because this branch is not permitted for docker build: ${GIT_BRANCH}"
fi